plugins {
    id 'com.android.application'
}

android {
    namespace 'com.lanchonete.tres.admin'
    compileSdk 35

    defaultConfig {
        applicationId 'com.lanchonete.tres.admin'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('com.google.firebase:firebase-bom:34.18.0')
    implementation 'com.google.firebase:firebase-messaging'
}
