// Múltiplas promoções clicáveis com valor fixo definido pelo administrador.
(() => {
  const KEY="__promotion_order__",section=$("#promoSection"),box=$("#selectedPromoBox"),boxTitle=$("#selectedPromoTitle"),boxPrice=$("#selectedPromoPrice");
  let promotions=[],selected=null;
  const chosen=()=>Boolean(selected?.id&&selected?.orderEnabled&&cart.has(KEY));
  function syncBox(){if(!box)return;box.hidden=!chosen();if(chosen()){boxTitle.textContent=selected.title||"Promoção";boxPrice.textContent=money(selected.price)}}
  const oldDetails=cartDetails;cartDetails=function(){const d=oldDetails();if(chosen()){d.count+=1;d.total=Number((d.total+Number(selected.price||0)).toFixed(2))}return d};
  const oldItems=orderItems;orderItems=function(){const items=oldItems();if(chosen())items.unshift({id:KEY,name:`Promoção: ${selected.title}`,qty:1,price:Number(selected.price||0),isPromotion:true,promotionId:selected.id});return items};
  const oldRender=renderCart;renderCart=function(){oldRender();if(chosen())cartItemsEl.insertAdjacentHTML("afterbegin",`<div class="cart-item promo-cart-item"><div><span class="promo-cart-label">PROMOÇÃO</span><strong>${esc(selected.title||"Promoção")}</strong><small>Valor promocional fixo</small><button class="remove-promo-button" type="button" data-remove-promo>Remover promoção</button></div><strong>${money(selected.price)}</strong></div>`);syncBox()};
  registerOrder=async function(formData){const regular=[...cart.entries()].map(([id,qty])=>{if(String(id)===KEY)return null;const p=products.find(x=>String(x.id)===String(id));return p?{id:String(p.id),name:p.name,qty}:null}).filter(Boolean);const payload={clientOrderId:clientOrderId(),localDate:localDateKey(),customerName:formData.get("customerName"),customerPhone:formData.get("customerPhone"),payment:formData.get("payment"),deliveryType:formData.get("deliveryType"),address:formData.get("address")||"",reference:formData.get("reference")||"",changeFor:formData.get("changeFor")||"",note:formData.get("orderNote")||"",promoId:chosen()?String(selected.id):"",items:regular};const data=await submitOrderPayload(payload);return Object.assign(data.order,{_messaging:data.messaging||null})};
  function normalize(data){const list=Array.isArray(data?.promotions)?data.promotions:[];return list.filter(p=>p?.active&&(p.image||p.title||p.description)).map(p=>({...p,id:String(p.id||""),price:Number(p.price||0),orderEnabled:Boolean(p.orderEnabled&&Number(p.price||0)>0)}))}
  function render(){if(!section)return;if(!promotions.length){section.hidden=true;selected=null;cart.delete(KEY);renderCart();return}section.innerHTML=`<div class="promo-list">${promotions.map(p=>{const has=Number.isFinite(p.price)&&p.price>0,orderable=p.orderEnabled&&has;return `<article class="promo-card ${orderable?"promo-orderable":"promo-unavailable"}" data-promo-id="${esc(p.id)}" ${orderable?`role="button" tabindex="0" aria-label="Pedir ${esc(p.title||"promoção")} por ${esc(money(p.price))}"`:""}>${p.image?`<img class="promo-image" src="${p.image}" alt="${esc(p.title||"Imagem da promoção")}">`:`<div class="promo-image promo-image-empty">PROMOÇÃO</div>`}<div class="promo-content"><span class="promo-label">PROMOÇÃO</span><h2>${esc(p.title||"Promoção")}</h2><p>${esc(p.description||"")}</p><div class="promo-order-meta">${has?`<strong class="promo-order-price">${money(p.price)}</strong>`:""}<button class="promo-order-button" type="button" data-promo-order="${esc(p.id)}" ${orderable?"":"disabled"}>${orderable?`Pedir esta promoção · ${money(p.price)}`:"Promoção indisponível"}</button><small class="promo-order-hint">${orderable?"Toque na promoção para ir direto ao pedido.":"Esta promoção está visível, mas indisponível para pedidos no momento."}</small></div></div></article>`}).join("")}</div>`;section.hidden=false}
  loadPromotion=async function(){try{const r=await fetch("/api/promos",{cache:"no-store"});if(!r.ok)throw new Error();promotions=normalize(await r.json());if(selected){const fresh=promotions.find(p=>p.id===selected.id&&p.orderEnabled);if(fresh)selected=fresh;else{selected=null;cart.delete(KEY)}}render();renderCart()}catch{try{const r=await fetch("/api/promo",{cache:"no-store"}),p=r.ok?await r.json():null;promotions=p?.active?normalize({promotions:[p]}):[];render();renderCart()}catch{promotions=[];render()}}};
  function choose(id){const p=promotions.find(x=>x.id===String(id));if(!p?.orderEnabled)return;selected=p;cart.set(KEY,1);renderCart();openCheckout()}
  section?.addEventListener("click",e=>{const b=e.target.closest("[data-promo-order]"),c=e.target.closest("[data-promo-id]"),id=b?.dataset.promoOrder||c?.dataset.promoId;if(!id)return;e.preventDefault();choose(id)});
  section?.addEventListener("keydown",e=>{if(e.key!=="Enter"&&e.key!==" ")return;const c=e.target.closest("[data-promo-id]");if(!c)return;e.preventDefault();choose(c.dataset.promoId)});
  document.addEventListener("click",e=>{const b=e.target.closest("[data-remove-promo]");if(!b)return;e.preventDefault();e.stopPropagation();selected=null;cart.delete(KEY);renderCart()});
  loadPromotion();
})();
